
USE [master]
GO

/****** Object:  Database [DLinqTests]    Script Date: 10/22/2025 4:43:42 PM ******/
CREATE DATABASE [DLinqTests]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DLinqTests', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SE16\Data\DLinqTests.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DLinqTests_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SE16\Data\DLinqTests_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DLinqTests].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DLinqTests] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DLinqTests] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DLinqTests] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DLinqTests] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DLinqTests] SET ARITHABORT OFF 
GO

ALTER DATABASE [DLinqTests] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DLinqTests] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DLinqTests] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DLinqTests] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DLinqTests] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DLinqTests] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DLinqTests] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DLinqTests] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DLinqTests] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DLinqTests] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DLinqTests] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DLinqTests] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DLinqTests] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DLinqTests] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DLinqTests] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DLinqTests] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DLinqTests] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DLinqTests] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DLinqTests] SET  MULTI_USER 
GO

ALTER DATABASE [DLinqTests] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DLinqTests] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DLinqTests] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DLinqTests] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DLinqTests] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DLinqTests] SET QUERY_STORE = OFF
GO

USE [DLinqTests]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [DLinqTests] SET  READ_WRITE 
GO


USE [DLinqTests]
GO
/****** Object:  Table [dbo].[Person]    Script Date: 10/22/2025 4:43:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Person](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Age] [int] NOT NULL,
	[CreateDateUTC] [datetime] NOT NULL,
 CONSTRAINT [PK_Person] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PersonUUID]    Script Date: 10/22/2025 4:43:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PersonUUID](
	[Id] [uniqueidentifier] NOT NULL,
	[FirstName] [varchar](100) NOT NULL,
	[LastName] [varchar](100) NOT NULL,
	[Age] [int] NOT NULL,
	[CreateDateUTC] [datetime] NOT NULL,
 CONSTRAINT [PK_PersonUUID] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
